Fix salesforce-update-sink.kamelet
At runtime the bean is renamed which seems to cause the
NoSuchEndpointException: No endpoint could be found for: local-salesforce-1

CMLK-2211 Kamelet salesforce-update-sink throws NoSuchEndpointException